using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Threading;
using UnityEngine;

public class ReadMap : MonoBehaviour
{
    [SerializeField]
    private TextAsset textFile;

    private string[] textData;
    private string[,] dungeonMap;

    private int tateNumber; // 行数に相当
    private int yokoNumber; // 列数に相当

    public GameObject D01;
    public GameObject D03;
    public GameObject D05;
    public GameObject D07;
    public GameObject D09;
    public GameObject D10;
    public GameObject D12;
    public GameObject D14;
    public GameObject D16;
    public GameObject D18;
    public GameObject D110;
    public GameObject D21;
    public GameObject D23;
    public GameObject D25;
    public GameObject D27;
    public GameObject D29;
    public GameObject D30;
    public GameObject D32;
    public GameObject D34;
    public GameObject D36;
    public GameObject D38;
    public GameObject D310;
    public GameObject D41;
    public GameObject D43;
    public GameObject D45;
    public GameObject D47;
    public GameObject D49;
    public GameObject D50;
    public GameObject D52;
    public GameObject D54;
    public GameObject D56;
    public GameObject D58;
    public GameObject D510;
    public GameObject D61;
    public GameObject D63;
    public GameObject D65;
    public GameObject D67;
    public GameObject D69;
    public GameObject D70;
    public GameObject D72;
    public GameObject D74;
    public GameObject D76;
    public GameObject D78;
    public GameObject D710;
    public GameObject D81;
    public GameObject D83;
    public GameObject D85;
    public GameObject D87;
    public GameObject D89;
    public GameObject D90;
    public GameObject D92;
    public GameObject D94;
    public GameObject D96;
    public GameObject D98;
    public GameObject D910;
    public GameObject D101;
    public GameObject D103;
    public GameObject D105;
    public GameObject D107;
    public GameObject D109;

    private void Start()
    {

        Thread.Sleep(500);
        string textLines = textFile.text; // テキストのデータの代入
        print(textLines);
        var locky = this.gameObject.GetComponent<BoxCollider>();
        var L01 = D01.gameObject.GetComponent<BoxCollider>();
        var L03 = D03.gameObject.GetComponent<BoxCollider>();
        var L05 = D05.gameObject.GetComponent<BoxCollider>();
        var L07 = D07.gameObject.GetComponent<BoxCollider>();
        var L09 = D09.gameObject.GetComponent<BoxCollider>();
        var L10 = D10.gameObject.GetComponent<BoxCollider>();
        var L12 = D12.gameObject.GetComponent<BoxCollider>();
        var L14 = D14.gameObject.GetComponent<BoxCollider>();
        var L16 = D16.gameObject.GetComponent<BoxCollider>();
        var L18 = D18.gameObject.GetComponent<BoxCollider>();
        var L110 = D110.gameObject.GetComponent<BoxCollider>();
        var L21 = D21.gameObject.GetComponent<BoxCollider>();
        var L23 = D23.gameObject.GetComponent<BoxCollider>();
        var L25 = D25.gameObject.GetComponent<BoxCollider>();
        var L27 = D27.gameObject.GetComponent<BoxCollider>();
        var L29 = D29.gameObject.GetComponent<BoxCollider>();
        var L30 = D30.gameObject.GetComponent<BoxCollider>();
        var L32 = D32.gameObject.GetComponent<BoxCollider>();
        var L34 = D34.gameObject.GetComponent<BoxCollider>();
        var L36 = D36.gameObject.GetComponent<BoxCollider>();
        var L38 = D38.gameObject.GetComponent<BoxCollider>();
        var L310 = D310.gameObject.GetComponent<BoxCollider>();
        var L41 = D41.gameObject.GetComponent<BoxCollider>();
        var L43 = D43.gameObject.GetComponent<BoxCollider>();
        var L45 = D45.gameObject.GetComponent<BoxCollider>();
        var L47 = D47.gameObject.GetComponent<BoxCollider>();
        var L49 = D49.gameObject.GetComponent<BoxCollider>();
        var L50 = D50.gameObject.GetComponent<BoxCollider>();
        var L52 = D52.gameObject.GetComponent<BoxCollider>();
        var L54 = D54.gameObject.GetComponent<BoxCollider>();
        var L56 = D56.gameObject.GetComponent<BoxCollider>();
        var L58 = D58.gameObject.GetComponent<BoxCollider>();
        var L510 = D510.gameObject.GetComponent<BoxCollider>();
        var L61 = D61.gameObject.GetComponent<BoxCollider>();
        var L63 = D63.gameObject.GetComponent<BoxCollider>();
        var L65 = D65.gameObject.GetComponent<BoxCollider>();
        var L67 = D67.gameObject.GetComponent<BoxCollider>();
        var L69 = D69.gameObject.GetComponent<BoxCollider>();
        var L70 = D70.gameObject.GetComponent<BoxCollider>();
        var L72 = D72.gameObject.GetComponent<BoxCollider>();
        var L74 = D74.gameObject.GetComponent<BoxCollider>();
        var L76 = D76.gameObject.GetComponent<BoxCollider>();
        var L78 = D78.gameObject.GetComponent<BoxCollider>();
        var L710 = D710.gameObject.GetComponent<BoxCollider>();
        var L81 = D81.gameObject.GetComponent<BoxCollider>();
        var L83 = D83.gameObject.GetComponent<BoxCollider>();
        var L85 = D85.gameObject.GetComponent<BoxCollider>();
        var L87 = D87.gameObject.GetComponent<BoxCollider>();
        var L89 = D89.gameObject.GetComponent<BoxCollider>();
        var L90 = D90.gameObject.GetComponent<BoxCollider>();
        var L92 = D92.gameObject.GetComponent<BoxCollider>();
        var L94 = D94.gameObject.GetComponent<BoxCollider>();
        var L96 = D96.gameObject.GetComponent<BoxCollider>();
        var L98 = D98.gameObject.GetComponent<BoxCollider>();
        var L910 = D910.gameObject.GetComponent<BoxCollider>();
        var L101 = D101.gameObject.GetComponent<BoxCollider>();
        var L103 = D103.gameObject.GetComponent<BoxCollider>();
        var L105 = D105.gameObject.GetComponent<BoxCollider>();
        var L107 = D107.gameObject.GetComponent<BoxCollider>();
        var L109 = D109.gameObject.GetComponent<BoxCollider>();
        D01.gameObject.GetComponent<MeshCollider>().enabled = false;
        D03.gameObject.GetComponent<MeshCollider>().enabled = false;
        D05.gameObject.GetComponent<MeshCollider>().enabled = false;
        D07.gameObject.GetComponent<MeshCollider>().enabled = false;
        D09.gameObject.GetComponent<MeshCollider>().enabled = false;
        D10.gameObject.GetComponent<MeshCollider>().enabled = false;
        D12.gameObject.GetComponent<MeshCollider>().enabled = false;
        D14.gameObject.GetComponent<MeshCollider>().enabled = false;
        D16.gameObject.GetComponent<MeshCollider>().enabled = false;
        D18.gameObject.GetComponent<MeshCollider>().enabled = false;
        D110.gameObject.GetComponent<MeshCollider>().enabled = false;
        D21.gameObject.GetComponent<MeshCollider>().enabled = false;
        D23.gameObject.GetComponent<MeshCollider>().enabled = false;
        D25.gameObject.GetComponent<MeshCollider>().enabled = false;
        D27.gameObject.GetComponent<MeshCollider>().enabled = false;
        D29.gameObject.GetComponent<MeshCollider>().enabled = false;
        D30.gameObject.GetComponent<MeshCollider>().enabled = false;
        D32.gameObject.GetComponent<MeshCollider>().enabled = false;
        D34.gameObject.GetComponent<MeshCollider>().enabled = false;
        D36.gameObject.GetComponent<MeshCollider>().enabled = false;
        D38.gameObject.GetComponent<MeshCollider>().enabled = false;
        D310.gameObject.GetComponent<MeshCollider>().enabled = false;
        D41.gameObject.GetComponent<MeshCollider>().enabled = false;
        D43.gameObject.GetComponent<MeshCollider>().enabled = false;
        D45.gameObject.GetComponent<MeshCollider>().enabled = false;
        D47.gameObject.GetComponent<MeshCollider>().enabled = false;
        D49.gameObject.GetComponent<MeshCollider>().enabled = false;
        D50.gameObject.GetComponent<MeshCollider>().enabled = false;
        D52.gameObject.GetComponent<MeshCollider>().enabled = false;
        D54.gameObject.GetComponent<MeshCollider>().enabled = false;
        D56.gameObject.GetComponent<MeshCollider>().enabled = false;
        D58.gameObject.GetComponent<MeshCollider>().enabled = false;
        D510.gameObject.GetComponent<MeshCollider>().enabled = false;
        D61.gameObject.GetComponent<MeshCollider>().enabled = false;
        D63.gameObject.GetComponent<MeshCollider>().enabled = false;
        D65.gameObject.GetComponent<MeshCollider>().enabled = false;
        D67.gameObject.GetComponent<MeshCollider>().enabled = false;
        D69.gameObject.GetComponent<MeshCollider>().enabled = false;
        D70.gameObject.GetComponent<MeshCollider>().enabled = false;
        D72.gameObject.GetComponent<MeshCollider>().enabled = false;
        D74.gameObject.GetComponent<MeshCollider>().enabled = false;
        D76.gameObject.GetComponent<MeshCollider>().enabled = false;
        D78.gameObject.GetComponent<MeshCollider>().enabled = false;
        D710.gameObject.GetComponent<MeshCollider>().enabled = false;
        D81.gameObject.GetComponent<MeshCollider>().enabled = false;
        D83.gameObject.GetComponent<MeshCollider>().enabled = false;
        D85.gameObject.GetComponent<MeshCollider>().enabled = false;
        D87.gameObject.GetComponent<MeshCollider>().enabled = false;
        D89.gameObject.GetComponent<MeshCollider>().enabled = false;
        D90.gameObject.GetComponent<MeshCollider>().enabled = false;
        D92.gameObject.GetComponent<MeshCollider>().enabled = false;
        D94.gameObject.GetComponent<MeshCollider>().enabled = false;
        D96.gameObject.GetComponent<MeshCollider>().enabled = false;
        D98.gameObject.GetComponent<MeshCollider>().enabled = false;
        D910.gameObject.GetComponent<MeshCollider>().enabled = false;
        D101.gameObject.GetComponent<MeshCollider>().enabled = false;
        D103.gameObject.GetComponent<MeshCollider>().enabled = false;
        D105.gameObject.GetComponent<MeshCollider>().enabled = false;
        D107.gameObject.GetComponent<MeshCollider>().enabled = false;
        D109.gameObject.GetComponent<MeshCollider>().enabled = false;
        D01.gameObject.GetComponent<BoxCollider>().enabled = true;
        D03.gameObject.GetComponent<BoxCollider>().enabled = true;
        D05.gameObject.GetComponent<BoxCollider>().enabled = true;
        D07.gameObject.GetComponent<BoxCollider>().enabled = true;
        D09.gameObject.GetComponent<BoxCollider>().enabled = true;
        D10.gameObject.GetComponent<BoxCollider>().enabled = true;
        D12.gameObject.GetComponent<BoxCollider>().enabled = true;
        D14.gameObject.GetComponent<BoxCollider>().enabled = true;
        D16.gameObject.GetComponent<BoxCollider>().enabled = true;
        D18.gameObject.GetComponent<BoxCollider>().enabled = true;
        D110.gameObject.GetComponent<BoxCollider>().enabled = true;
        D21.gameObject.GetComponent<BoxCollider>().enabled = true;
        D23.gameObject.GetComponent<BoxCollider>().enabled = true;
        D25.gameObject.GetComponent<BoxCollider>().enabled = true;
        D27.gameObject.GetComponent<BoxCollider>().enabled = true;
        D29.gameObject.GetComponent<BoxCollider>().enabled = true;
        D30.gameObject.GetComponent<BoxCollider>().enabled = true;
        D32.gameObject.GetComponent<BoxCollider>().enabled = true;
        D34.gameObject.GetComponent<BoxCollider>().enabled = true;
        D36.gameObject.GetComponent<BoxCollider>().enabled = true;
        D38.gameObject.GetComponent<BoxCollider>().enabled = true;
        D310.gameObject.GetComponent<BoxCollider>().enabled = true;
        D41.gameObject.GetComponent<BoxCollider>().enabled = true;
        D43.gameObject.GetComponent<BoxCollider>().enabled = true;
        D45.gameObject.GetComponent<BoxCollider>().enabled = true;
        D47.gameObject.GetComponent<BoxCollider>().enabled = true;
        D49.gameObject.GetComponent<BoxCollider>().enabled = true;
        D50.gameObject.GetComponent<BoxCollider>().enabled = true;
        D52.gameObject.GetComponent<BoxCollider>().enabled = true;
        D54.gameObject.GetComponent<BoxCollider>().enabled = true;
        D56.gameObject.GetComponent<BoxCollider>().enabled = true;
        D58.gameObject.GetComponent<BoxCollider>().enabled = true;
        D510.gameObject.GetComponent<BoxCollider>().enabled = true;
        D61.gameObject.GetComponent<BoxCollider>().enabled = true;
        D63.gameObject.GetComponent<BoxCollider>().enabled = true;
        D65.gameObject.GetComponent<BoxCollider>().enabled = true;
        D67.gameObject.GetComponent<BoxCollider>().enabled = true;
        D69.gameObject.GetComponent<BoxCollider>().enabled = true;
        D70.gameObject.GetComponent<BoxCollider>().enabled = true;
        D72.gameObject.GetComponent<BoxCollider>().enabled = true;
        D74.gameObject.GetComponent<BoxCollider>().enabled = true;
        D76.gameObject.GetComponent<BoxCollider>().enabled = true;
        D78.gameObject.GetComponent<BoxCollider>().enabled = true;
        D710.gameObject.GetComponent<BoxCollider>().enabled = true;
        D81.gameObject.GetComponent<BoxCollider>().enabled = true;
        D83.gameObject.GetComponent<BoxCollider>().enabled = true;
        D85.gameObject.GetComponent<BoxCollider>().enabled = true;
        D87.gameObject.GetComponent<BoxCollider>().enabled = true;
        D89.gameObject.GetComponent<BoxCollider>().enabled = true;
        D90.gameObject.GetComponent<BoxCollider>().enabled = true;
        D92.gameObject.GetComponent<BoxCollider>().enabled = true;
        D94.gameObject.GetComponent<BoxCollider>().enabled = true;
        D96.gameObject.GetComponent<BoxCollider>().enabled = true;
        D98.gameObject.GetComponent<BoxCollider>().enabled = true;
        D910.gameObject.GetComponent<BoxCollider>().enabled = true;
        D101.gameObject.GetComponent<BoxCollider>().enabled = true;
        D103.gameObject.GetComponent<BoxCollider>().enabled = true;
        D105.gameObject.GetComponent<BoxCollider>().enabled = true;
        D107.gameObject.GetComponent<BoxCollider>().enabled = true;
        D109.gameObject.GetComponent<BoxCollider>().enabled = true;

        // 改行でデータを分割して配列に代入
        textData = textLines.Split('\n');

        // 行数と列数の取得
        yokoNumber = textData[0].Split(',').Length;
        tateNumber = textData.Length;

        print("tate" + tateNumber);
        print("yoko" + yokoNumber);

        // ２次元配列の定義
        dungeonMap = new string[tateNumber, yokoNumber];

        for (int i = 0; i < tateNumber; i++)
        {
            string[] tempWords = textData[i].Split(',');

            for (int j = 0; j < yokoNumber; j++)
            {
                dungeonMap[i, j] = tempWords[j];
                }
            }
        if (dungeonMap[0, 1] == "O") L01.enabled = false;
        if (dungeonMap[0, 3] == "O") L03.enabled = false;
        if (dungeonMap[0, 5] == "O") L05.enabled = false;
        if (dungeonMap[0, 7] == "O") L07.enabled = false;
        if (dungeonMap[0, 9] == "O") L09.enabled = false;
        if (dungeonMap[1, 0] == "O") L10.enabled = false;
        if (dungeonMap[1, 2] == "O") L12.enabled = false;
        if (dungeonMap[1, 4] == "O") L14.enabled = false;
        if (dungeonMap[1, 6] == "O") L16.enabled = false;
        if (dungeonMap[1, 8] == "O") L18.enabled = false;
        if (dungeonMap[1, 10] == "O") L110.enabled = false;
        if (dungeonMap[2, 1] == "O") L21.enabled = false;
        if (dungeonMap[2, 3] == "O") L23.enabled = false;
        if (dungeonMap[2, 5] == "O") L25.enabled = false;
        if (dungeonMap[2, 7] == "O") L27.enabled = false;
        if (dungeonMap[2, 9] == "O") L29.enabled = false;
        if (dungeonMap[3, 0] == "O") L30.enabled = false;
        if (dungeonMap[3, 2] == "O") L32.enabled = false;
        if (dungeonMap[3, 4] == "O") L34.enabled = false;
        if (dungeonMap[3, 6] == "O") L36.enabled = false;
        if (dungeonMap[3, 8] == "O") L38.enabled = false;
        if (dungeonMap[3, 10] == "O") L310.enabled = false;
        if (dungeonMap[4, 1] == "O") L41.enabled = false;
        if (dungeonMap[4, 3] == "O") L43.enabled = false;
        if (dungeonMap[4, 5] == "O") L45.enabled = false;
        if (dungeonMap[4, 7] == "O") L47.enabled = false;
        if (dungeonMap[4, 9] == "O") L49.enabled = false;
        if (dungeonMap[5, 0] == "O") L50.enabled = false;
        if (dungeonMap[5, 2] == "O") L52.enabled = false;
        if (dungeonMap[5, 4] == "O") L54.enabled = false;
        if (dungeonMap[5, 6] == "O") L56.enabled = false;
        if (dungeonMap[5, 8] == "O") L58.enabled = false;
        if (dungeonMap[5, 10] == "O") L510.enabled = false;
        if (dungeonMap[6, 1] == "O") L61.enabled = false;
        if (dungeonMap[6, 3] == "O") L63.enabled = false;
        if (dungeonMap[6, 5] == "O") L65.enabled = false;
        if (dungeonMap[6, 7] == "O") L67.enabled = false;
        if (dungeonMap[6, 9] == "O") L69.enabled = false;
        if (dungeonMap[7, 0] == "O") L70.enabled = false;
        if (dungeonMap[7, 2] == "O") L72.enabled = false;
        if (dungeonMap[7, 4] == "O") L74.enabled = false;
        if (dungeonMap[7, 6] == "O") L76.enabled = false;
        if (dungeonMap[7, 8] == "O") L78.enabled = false;
        if (dungeonMap[7, 10] == "O") L710.enabled = false;
        if (dungeonMap[8, 1] == "O") L81.enabled = false;
        if (dungeonMap[8, 3] == "O") L83.enabled = false;
        if (dungeonMap[8, 5] == "O") L85.enabled = false;
        if (dungeonMap[8, 7] == "O") L87.enabled = false;
        if (dungeonMap[8, 9] == "O") L89.enabled = false;
        if (dungeonMap[9, 0] == "O") L90.enabled = false;
        if (dungeonMap[9, 2] == "O") L92.enabled = false;
        if (dungeonMap[9, 4] == "O") L94.enabled = false;
        if (dungeonMap[9, 6] == "O") L96.enabled = false;
        if (dungeonMap[9, 8] == "O") L98.enabled = false;
        if (dungeonMap[9, 10] == "O") L910.enabled = false;
        if (dungeonMap[10, 1] == "O") L101.enabled = false;
        if (dungeonMap[10, 3] == "O") L103.enabled = false;
        if (dungeonMap[10, 5] == "O") L105.enabled = false;
        if (dungeonMap[10, 7] == "O") L107.enabled = false;
        if (dungeonMap[10, 9] == "O") L109.enabled = false;
        print(L10.enabled);
    }
}